### ISSUE TITLE
Unexpected behavior with "Confirm false"

### ISSUE THREAD

**Issue by mikekab** [ClemsonRSRG/RESOLVE#246]
To reproduce generate VCs from something similar to:
```
	Operation Do_Nothing(restores I,J: Integer);
	requires I + 1 < I;
	Procedure
		Confirm false;
	end Do_Nothing;
```
What happens:
```
VC 0_1

Explicit Confirm Statement: Int_Do_Nothing_Exercise.fa(8)

Goal(s):

false

Given(s):


```

What I think should happen:

```
VC 0_1

Explicit Confirm Statement: Int_Do_Nothing_Exercise.fa(8)

Goal(s):

false

Given(s):

 I + 1 < I
```

We can still prove some statements with a false conclusion.

**Comment by yushan87** [comment]
I don't think this is a problem. While I agree this requires clause would allow you to prove anything in the code, it isn't something that is realistic. There is no way a caller of `Do_Nothing` would ever be able to satisfy the pre-condition. 

The next question you might ask is: what if the requires clause said `requires false;`. In that case, I believe it would be a given for all goals that contain `false` somewhere. This is because the parsimonious VC generation checks to see if any of the assume expression's symbols appear in the goal. If it does, then we add it as a given to the goal. If not, we assume it would not be useful. Note that this only applies to regular `Assume` statements. If any of our rules generate a `Stipulate (Assume)` statement, it will always add the expression as a given.
